# Generated by Django 5.0.6 on 2024-06-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_alter_carrito_image_alter_productos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='image',
            field=models.ImageField(blank=True, upload_to='carrito'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(blank=True, upload_to='productos'),
        ),
    ]
