# Generated by Django 5.0.6 on 2024-06-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_alter_carrito_image_alter_productos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
